### PR TITLE
Regenerate C code with recent version of Cython

### PR DESCRIPTION
**Pull request by dmand**
To be more specific, Cython 0.29 was used.

This will make the project installable under Python 3.7, as it fails to build with the following errors from gcc:

```
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/fuzzyset
copying fuzzyset/__init__.py -> build/lib.linux-x86_64-3.7/fuzzyset
running build_ext
building 'cfuzzyset' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/fuzzyset
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/dmand/.pythonz/pythons/CPython-3.7.1/include/python3.7m -c fuzzyset/cfuzzyset.c -o build/temp.linux-x86_64-3.7/fuzzyset/cfuzzyset.o
fuzzyset/cfuzzyset.c: In function ‘__Pyx__ExceptionSave’:
fuzzyset/cfuzzyset.c:6985:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
fuzzyset/cfuzzyset.c:6986:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     *value = tstate->exc_value;
                      ^~~~~~~~~
                      curexc_value
fuzzyset/cfuzzyset.c:6987:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     *tb = tstate->exc_traceback;
                   ^~~~~~~~~~~~~
                   curexc_traceback
fuzzyset/cfuzzyset.c: In function ‘__Pyx__ExceptionReset’:
fuzzyset/cfuzzyset.c:6994:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
fuzzyset/cfuzzyset.c:6995:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
fuzzyset/cfuzzyset.c:6996:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
fuzzyset/cfuzzyset.c:6997:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = type;
             ^~~~~~~~
             curexc_type
fuzzyset/cfuzzyset.c:6998:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = value;
             ^~~~~~~~~
             curexc_value
fuzzyset/cfuzzyset.c:6999:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = tb;
             ^~~~~~~~~~~~~
             curexc_traceback
fuzzyset/cfuzzyset.c: In function ‘__Pyx__GetException’:
fuzzyset/cfuzzyset.c:7054:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
fuzzyset/cfuzzyset.c:7055:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
fuzzyset/cfuzzyset.c:7056:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
fuzzyset/cfuzzyset.c:7057:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = local_type;
             ^~~~~~~~
             curexc_type
fuzzyset/cfuzzyset.c:7058:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = local_value;
             ^~~~~~~~~
             curexc_value
fuzzyset/cfuzzyset.c:7059:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = local_tb;
             ^~~~~~~~~~~~~
             curexc_traceback
error: command 'gcc' failed with exit status 1
```

### CODE REVIEW

**Comment by r-chris** [comment]
I'm seeing this exact same issue. Would be great to have this resolved.

**Comment by dmand** [comment]
@r-chris as a temporary solution, you can install fuzzyset from my fork: `pip install git+https://github.com/dmand/fuzzyset.git@regenerate-cython-for-python-3.7#egg=fuzzyset`

This is for experiments only, of course. Not for production use.

**Comment by axiak** [comment]
This should be fixed on the most recent version, 0.0.16

**Comment by dmand** [comment]
Thanks!

**Pull request closed without merging**
