### PR TITLE
fixes #28

### LINKED ISSUE #28: Problem with install to Python3.9
pip install fuzzyset
trace 
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1t1vw2c7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fuzzyset
         cwd: /tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/
    Complete output (137 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/fuzzyset
    copying fuzzyset/__init__.py -> build/lib.linux-x86_64-3.9/fuzzyset
    running build_ext
    building 'cfuzzyset' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/fuzzyset
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c fuzzyset/cfuzzyset.c -o build/temp.linux-x86_64-3.9/fuzzyset/cfuzzyset.o
    fuzzyset/cfuzzyset.c: In function '__Pyx_modinit_type_init_code':
    fuzzyset/cfuzzyset.c:6309:35: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'; did you mean 'tp_dict'?
       __pyx_type_9cfuzzyset_cFuzzySet.tp_print = 0;
                                       ^~~~~~~~
                                       tp_dict
    fuzzyset/cfuzzyset.c: In function '__Pyx_ParseOptionalKeywords':
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6778:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                         (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                         ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: 'PyUnicode_AsUnicode' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
                                                 ^~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c:6794:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
                             (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                             ^
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
     static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    fuzzyset/cfuzzyset.c: In function '__Pyx_PyUnicode_Substring':
    fuzzyset/cfuzzyset.c:8026:9: warning: 'PyUnicode_FromUnicode' is deprecated [-Wdeprecated-declarations]
             return PyUnicode_FromUnicode(NULL, 0);
             ^~~~~~
    In file included from /usr/local/include/python3.9/unicodeobject.h:1026,
                     from /usr/local/include/python3.9/Python.h:97,
                     from fuzzyset/cfuzzyset.c:4:
    /usr/local/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
                                              ^~~~~~~~~~~~~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-byd1csue/fuzzyset_7135df109e3b4107a8adf8352d3dea6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1t1vw2c7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/fuzzyset Check the logs for full command output.

### PR DESCRIPTION
**Pull request by alpae**
This PR should enable installing fuzzyset on python3.9

### CODE REVIEW

**Comment by alpae** [comment]
sorry about the confustion with the issue number. should fix #28

**Comment by hadjilucasL** [comment]
Thanks for this !
You probably need to up the version, and add @axiak as a reviewer ?

**Comment by alpae** [comment]
Hi @hadjilucasL, I think bumping the version is up to the package maintainer, isn't it? and I don't know how to add @axiak  as a reviewer... also, it is actually not some manual code change, but only regenerated cfuzzset.c with a newer version of cython...

**Comment by rgreid** [comment]
Bumping this.  In the meantime, `pip install git+https://github.com/alpae/fuzzyset` will install @alpae's branch

**Comment by uriva** [comment]
@axiak can someone merge and release this?

**Comment by alpae** [comment]
@axiak would be nice if you would merge this change and make a new release. python3.9 is out for quite some time and is now used by many users. Thanks

**Comment by alpae** [comment]
Hi @axiak  

I would really appreciate if you would merge this PR. I'm also willing to help maintaining the project, the latest commits would allow to deploy wheels directly to pypi on version tagged commits using github actions. 

if you no longer have time to maintain this project, I'm happy to take it over, or be added as an admin to this repo. If I don't hear anything back from you I'm considering maintaining a fork on pypi myself, which I really don't thing would be a good thing.

**Review by uriva — APPROVED** [review]

**Pull request merged**
